services:
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9001:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev